name: flutter_samples

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0-nullsafety
  font_awesome_flutter: ^9.0.0-nullsafety
  intl: ^0.17.0-nullsafety.2
  shimmer: ^2.0.0-nullsafety.0
  audioplayers: ^0.18.3
  cupertino_icons: ^1.0.2
  confetti: ^0.7.0
  page_transition: ^2.0.9
  provider: ^6.0.3
  fluttertoast: ^8.0.9
  curved_navigation_bar: ^1.0.3
  flutter_speed_dial: ^6.0.0
  flutter_zoom_drawer: ^3.0.3
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/characters/
    - assets/twitter_profile/
    - assets/balls/
    - assets/shoes/
    - assets/credit_cards/
    - assets/hotel_booking/
    - assets/fitness_app/
    - assets/flipping_card/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
